# Generated by Django 5.0.6 on 2024-09-12 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cesta",
            name="status",
            field=models.CharField(
                choices=[("pago", "Pago"), ("pendente", "Pendente")],
                default="pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="itemcesta",
            name="cesta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.cesta"
            ),
        ),
    ]
