# Generated by Django 5.1.1 on 2024-09-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_cesta_status_alter_itemcesta_cesta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="preco",
            new_name="preco_venda",
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_compra",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
