# Generated by Django 5.1.1 on 2024-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_rename_preco_produto_preco_venda_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcesta",
            name="preco_unitario",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
