# Generated by Django 5.1.1 on 2024-09-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_historicopreco"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicopreco",
            old_name="preco_antigo",
            new_name="preco_compra_antigo",
        ),
        migrations.RenameField(
            model_name="historicopreco",
            old_name="preco_novo",
            new_name="preco_compra_novo",
        ),
        migrations.AddField(
            model_name="historicopreco",
            name="preco_venda_antigo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicopreco",
            name="preco_venda_novo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
